SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[FT_LISTAR_PRODINV] () RETURNS @tabla TABLE(
IDEQ INT, 
NOMEQ NCHAR(100), 
PREEQ FLOAT, 
MAREQ NCHAR(100), 
MODEQ NCHAR(100),
ESTEQ NCHAR(1),
CNTINV INT
)
AS
BEGIN
	
	DECLARE @IDEQ INT
	DECLARE @NOMEQ NCHAR(100) 
	DECLARE @PREEQ FLOAT
	DECLARE @MAREQ NCHAR(100)
	DECLARE @MODEQ NCHAR(100)
	DECLARE @ESTEQ NCHAR(1)

	DECLARE @suma int
	DECLARE @resta int

	DECLARE cursorEquipo CURSOR FOR SELECT IDEQ, NOMEQ, PREEQ, MAREQ, MODEQ ,ESTEQ FROM EQUIPO;
	 OPEN cursorEquipo;  
		FETCH NEXT FROM cursorEquipo INTO @IDEQ, @NOMEQ, @PREEQ, @MAREQ, @MODEQ ,@ESTEQ;
		WHILE @@FETCH_STATUS = 0  
		   BEGIN 
				SELECT @suma=0, @resta=0;

				SELECT @suma=SUM(CNTINV) FROM INVENTARIO inv
				GROUP BY inv.IDEQ, inv.TIPINV
				HAVING inv.TIPINV = 'E' AND inv.IDEQ=@IDEQ;

				SELECT @resta=SUM(CNTINV) FROM INVENTARIO inv
				GROUP BY inv.IDEQ, inv.TIPINV
				HAVING inv.TIPINV = 'S' AND inv.IDEQ=@IDEQ;


				INSERT INTO @tabla(IDEQ, NOMEQ, PREEQ, MAREQ, MODEQ ,ESTEQ, CNTINV)
				VALUES (@IDEQ, @NOMEQ, @PREEQ, @MAREQ, @MODEQ ,@ESTEQ, @suma - @resta)

			FETCH NEXT FROM cursorEquipo INTO @IDEQ, @NOMEQ, @PREEQ, @MAREQ, @MODEQ ,@ESTEQ;
		   END;  
		CLOSE cursorEquipo;  
		DEALLOCATE cursorEquipo;
RETURN
END
GO
