CREATE TABLE [dbo].[EQUIPO]
(
[IDEQ] [int] NOT NULL IDENTITY(1, 1),
[NOMEQ] [nchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PREEQ] [float] NOT NULL,
[MAREQ] [nchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[MODEQ] [nchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTEQ] [nchar] (1) COLLATE Modern_Spanish_CI_AS NOT NULL CONSTRAINT [DF_EQUIPO_ESTEQ] DEFAULT (N'A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EQUIPO] ADD CONSTRAINT [PK_EQUIPO] PRIMARY KEY CLUSTERED  ([IDEQ]) ON [PRIMARY]
GO
