CREATE TABLE [dbo].[SUCURSAL]
(
[IDSUC] [int] NOT NULL IDENTITY(1, 1),
[NOMSUC] [nchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRSUC] [nchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTSUC] [nchar] (1) COLLATE Modern_Spanish_CI_AS NOT NULL CONSTRAINT [DF_SUCURSAL_ESTSUC] DEFAULT (N'A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUCURSAL] ADD CONSTRAINT [PK_SUCURSAL] PRIMARY KEY CLUSTERED  ([IDSUC]) ON [PRIMARY]
GO
