CREATE TABLE [dbo].[VENTA_DETALLE]
(
[IDVENDET] [int] NOT NULL IDENTITY(1, 1),
[CNTVEN] [int] NOT NULL,
[IDEQ] [int] NOT NULL,
[TOTVENDET] [float] NOT NULL,
[IDVEN] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [PK_VENTA_DETALLE] PRIMARY KEY CLUSTERED  ([IDVENDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [EQUIPO_VENTA_DETALLE_IDEQ] FOREIGN KEY ([IDEQ]) REFERENCES [dbo].[EQUIPO] ([IDEQ])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_VENTA_DETALLE_IDVEN] FOREIGN KEY ([IDVEN]) REFERENCES [dbo].[VENTA] ([IDVEN])
GO
