CREATE TABLE [dbo].[PERSONA]
(
[IDPER] [int] NOT NULL IDENTITY(1, 1),
[NOMPER] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEPER] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRPER] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[DNIPER] [nchar] (8) COLLATE Modern_Spanish_CI_AS NULL,
[ESTPER] [nchar] (1) COLLATE Modern_Spanish_CI_AS NULL CONSTRAINT [DF_PERSONA_ESTPER] DEFAULT (N'A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PK_PERSONA] PRIMARY KEY CLUSTERED  ([IDPER]) ON [PRIMARY]
GO
