CREATE TABLE [dbo].[PERSONA]
(
[IDPER] [int] NOT NULL IDENTITY(1, 1),
[NOMPER] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEPER] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRPER] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[DNIPER] [nchar] (8) COLLATE Modern_Spanish_CI_AS NULL,
[ESTPER] [nchar] (1) COLLATE Modern_Spanish_CI_AS NULL CONSTRAINT [DF_PERSONA_ESTPER] DEFAULT (N'A')
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Trigger para no tener redundancia a la hora de registrar personas
CREATE TRIGGER [dbo].[TR_REGPER_VALIDACION]
ON [dbo].[PERSONA] INSTEAD OF INSERT
AS
BEGIN
	
	IF((SELECT DNIPER FROM inserted) IS NOT NULL)
	BEGIN
		IF NOT EXISTS (
		SELECT DNIPER FROM PERSONA 
		WHERE DNIPER = (SELECT DNIPER FROM inserted)
		)
		BEGIN
			INSERT INTO PERSONA
			(NOMPER, APEPER, DNIPER, DIRPER)
			SELECT NOMPER, APEPER, DNIPER, DIRPER FROM inserted
		END
		ELSE
		BEGIN
			RAISERROR('[Error] El DNI ingresado ya existe.',10,1)
			ROLLBACK TRANSACTION
		END
	END
	ELSE
	BEGIN
		IF NOT EXISTS (
		SELECT IDPER FROM PERSONA 
		WHERE NOMPER = (SELECT NOMPER FROM inserted) 
		AND APEPER = (SELECT APEPER FROM inserted)
		)
		BEGIN
			INSERT INTO PERSONA
			(NOMPER, APEPER, DNIPER, DIRPER)
			SELECT NOMPER, APEPER, DNIPER, DIRPER FROM inserted
		END
		ELSE
		BEGIN
			RAISERROR('[Error] Los nombres y apellidos ingresados ya existen.',10,1)
			ROLLBACK TRANSACTION
		END
	END
END
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PK_PERSONA] PRIMARY KEY CLUSTERED  ([IDPER]) ON [PRIMARY]
GO
