CREATE TABLE [dbo].[TRABAJADOR]
(
[IDTRAB] [int] NOT NULL IDENTITY(1, 1),
[IDPER] [int] NOT NULL,
[FECINITRAB] [date] NOT NULL,
[FECFINTRAB] [date] NULL,
[ESTTRAB] [nchar] (1) COLLATE Modern_Spanish_CI_AS NULL CONSTRAINT [DF_TRABAJADOR_ESTTRAB] DEFAULT (N'A'),
[TIPTRAB] [nchar] (1) COLLATE Modern_Spanish_CI_AS NULL,
[IDSUC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRABAJADOR] ADD CONSTRAINT [PK_TRABAJADOR] PRIMARY KEY CLUSTERED  ([IDTRAB]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRABAJADOR] ADD CONSTRAINT [PERSONA_TRABAJADOR_IDPER] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
ALTER TABLE [dbo].[TRABAJADOR] ADD CONSTRAINT [SUCURSAL_TRABAJADOR_IDSUC] FOREIGN KEY ([IDSUC]) REFERENCES [dbo].[SUCURSAL] ([IDSUC])
GO
