CREATE TABLE [dbo].[LOGIN]
(
[IDLOG] [int] NOT NULL IDENTITY(1, 1),
[TIPLOG] [nchar] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTLOG] [nchar] (1) COLLATE Modern_Spanish_CI_AS NOT NULL CONSTRAINT [DF_LOGIN_ESTLOG] DEFAULT (N'A'),
[IDTRAB] [int] NOT NULL,
[USRLOG] [nchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PSSWLOG] [nchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOGIN] ADD CONSTRAINT [PK_LOGIN] PRIMARY KEY CLUSTERED  ([IDLOG]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOGIN] ADD CONSTRAINT [TRABAJADOR_LOGID_IDTRAB] FOREIGN KEY ([IDTRAB]) REFERENCES [dbo].[TRABAJADOR] ([IDTRAB])
GO
