CREATE TABLE [dbo].[VENTA]
(
[IDVEN] [int] NOT NULL IDENTITY(1, 1),
[FECVEN] [date] NOT NULL CONSTRAINT [DF_Constraint] DEFAULT (getdate()),
[ETSVEN] [nchar] (1) COLLATE Modern_Spanish_CI_AS NOT NULL CONSTRAINT [DF_VENTA_ETSVEN] DEFAULT (N'A'),
[IDLOG] [int] NOT NULL,
[IDPER] [int] NOT NULL,
[TOTVEN] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [PK_VENTA] PRIMARY KEY CLUSTERED  ([IDVEN]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [LOGIN_VENTA_IDLOG] FOREIGN KEY ([IDLOG]) REFERENCES [dbo].[LOGIN] ([IDLOG])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [PERSONA_VENTA_IDPER] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
